language: node_js
node_js: 
  - 14.7.0

cache: yarn

install:
  - yarn install

script:
  - yarn test
  - yarn run express --touch
  - yarn run koa --touch
  - yarn run hapi --touch
  - yarn build
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

notifications:
  email:
    recipients:
      - eric14706@gmail.com
    on_success: never
    on_failure: always

# before_install:
# install:
# before_script:
# script:
# after_success:
# after_failure:
# after_script:
# before_deploy:
